### ISSUE TITLE
archive_entry_stat does not seem to work

### ISSUE THREAD

**Issue by ribasushi** [plicease/Archive-Libarchive-XS#39]
The attached example program produces 2 bytes as a result of calling `archive_entry_stat`. Based on the rest of the fields within the same entry, the result should be much larger:
```
Found file named 'foo' in tarball
  queried 'stat':	10	(2 bytes)
  queried 'dev':	1	(1 bytes)
  queried 'ino':	1	(1 bytes)
  queried 'mode':	33188	(5 bytes)
  queried 'nlink':	0	(1 bytes)
  queried 'uid':	1000	(4 bytes)
  queried 'gid':	1000	(4 bytes)
  queried 'rdev':	0	(1 bytes)
  queried 'size':	4	(1 bytes)
  queried 'birthtime':	0	(1 bytes)
  queried 'atime':	0	(1 bytes)
  queried 'mtime':	1498488689	(10 bytes)
  queried 'ctime':	0	(1 bytes)
Contents: 'bar
'
```
[arch_stat_wtf.txt](https://github.com/plicease/Archive-Libarchive-XS/files/1161528/arch_stat_wtf.txt)

**Comment by plicease** [comment]
archive_entry_stat returns a list:

https://metacpan.org/pod/distribution/Archive-Libarchive-XS/lib/Archive/Libarchive/XS/Function.pod#archive_entry_stat

**Comment by ribasushi** [comment]
Sigh... I completely misread the page, and then stupidly misconstructed the testcase.
Apologies for the noise.
